name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Latest Checkout Action (Node.js warning hatane ke liye v4 use kiya)
      - uses: actions/checkout@v4

      # 2. Latest Java Setup
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Flutter Setup
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '' # Automatically latest stable version uthayega

      # 4. Get Packages
      - name: Install dependencies
        run: flutter pub get

      # 5. Build Release APK (Direct build chala rahe hain testing check karne ke liye)
      - name: Build Release APK
        run: flutter build apk --release

      # 6. Upload Generated APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-apk
          path: build/app/outputs/flutter-apk/app-release.apk